version: '3.8'

services:
  empire-server:
    container_name: empire-server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    image: empire-server:latest
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - MongoDB__ConnectionString=${MONGODB_URI}
      - MongoDB__DatabaseName=Empire-Deckbuilder
    restart: unless-stopped
    # Limit memory to prevent build issues
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  run-sanitizer:
    image: empire-server:latest
    depends_on:
      - empire-server
    command: ["dotnet", "Empire.Server.dll", "--sanitize"]
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - MongoDB__ConnectionString=${MONGODB_URI}
      - MongoDB__DatabaseName=Empire-Deckbuilder
    restart: "no"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      # Remove blazor-dist volume that was causing issues
      # Card images should be served from CDN or external storage
    depends_on:
      - empire-server
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    restart: unless-stopped
