version: '3.8'

services:
  empire-server:
    container_name: empire-server
    build:
      context: .
      dockerfile: Dockerfile  # Adjust if yours has a different name
    image: empire-server:latest  # Optionally use the built image
    ports:
      - "5000:80"  # Exposes port 80 inside the container as port 5000 on the host
    environment:
      - ASPNETCORE_ENVIRONMENT=Production  # Set environment to Production
    restart: unless-stopped  # Automatically restart unless manually stopped

  # Optional NGINX container if you want to dockerize NGINX too
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot      # ✅ Add this
      - ./certbot/conf:/etc/letsencrypt     # ✅ Add this
    depends_on:
      - empire-server

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt

