version: '3.8'

services:
  empire-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: empire-tcg
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - empire-data:/app/data
    networks:
      - empire-network
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    container_name: empire-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - certbot-data:/var/www/certbot
    networks:
      - empire-network
    depends_on:
      - empire-app

  certbot:
    image: certbot/certbot
    container_name: empire-certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - certbot-data:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email your-email@domain.com --agree-tos --no-eff-email -d your-domain.com
    networks:
      - empire-network

volumes:
  empire-data:
    driver: local
  certbot-data:
    driver: local

networks:
  empire-network:
    driver: bridge
